
POST http://localhost:3001/api/blogs HTTP/1.1
Content-Type: application/json
Authorization: Bearer $2b$10$kpLOMJ0QSDTOHkoGrWdST.RD90JSKY3H07pbKhosa7tMDAVcT69cS

{
  "title": "Testing an app with login",
  "author": "Who R You",
  "url": "https://some.place.com",
  "likes": 5
}
