sequenceDiagram
    participant browser
    participant server

    Note right of browser: The user send new note with button Save
    browser->>server: POST https://studies.cs.helsinki.fi/exampleapp/new_note_spa
    activate server   
    Note right of browser: Server response
    server->>browser: HTTP 201 Created
    deactivate server
    


